adjective1 = input("Enter an adjective: ")
noun1 = input("Enter a noun: ")
adjective2 = input("Enter another adjective: ")
verb1 = input("Enter a verb: ")
adjective3 = input("Enter one more adjective: ")
print(f"Today I went to a {adjective1} zoo!")
print(f"I saw a {noun1}  at the zoo!")
print(f"{noun1} was {adjective2} and very {verb1}!")
print(f"I was {adjective3}")